#+title: Physics
#+startup: inlineimages

* The Science of Chronos
The Science of Chronos is a journal written by Arash Khosravi. A physicist who was in a state of chrogenic freeze, within a vaccuum tube, and sustained for nearly 20,000 years before his body, and still functioning chryogenic tube. He was revived in this new age. The rest is his account as he tried to bring himself up to speed with the progression of physics, science, and culture for the last 20,000 earth years.

One of the things he has learned, is that while in his age, science was overly focused on the "how" or "what". He learned this new (to him) age, science is the study of relationships, how things interact. Existence is relationships. And Arash's time had always treated relationships as a result of reality, and not the other way around. Philosophy s now concerned about the interconnectedness of all things. How our relationships shape our identities and our understanding of the  world. Relationships is what gives life meaning.

** Laws of Physics
*** There are no constants in nature, other than that there are constantly no constants
In the history of science, constants have come and gone.
1. Ptolemy's epicycles, deferents, and the equant point.
2. Roger Bacon's refractive index
3. Kepler's laws of planetary motion
4. Galileo's law of acceleration
5. Descartes quantity of motion
6. Newton's gravitational constant, laws of inertia, theory of time
7. Isaac Newton's speed of sound
8. Coulomb's electrostatic constant
9. Boyle, Charles, and Gay-Lussac's ideal gas constant
10. Universal Gas Constant
11. Atomic weights as constants in chemistry
In the history in relation to the Age of Chronos, more constants have come and gone.
1. Boltzmann Constant
2. The speed of light in a vaccuum
3. Einstein's gravitational constant
4. Planck's constant
5. The Cosmological constant
*** Constants are useful in eliminating sporadic concerns in order to make a model simple
Constants are useful in models and should be used freely, where applicable. But it is important to understand that all constants are relative to specific conditions that might not yet be possible to identify. If you happen to inhabit planet earth in the Solaris star system, you'll find many mundane uses for Newton's physics, provided you don't travell too far from sea level.
*** We always outgrow models
