#+title: Time Dilation
#+startup: inlineimages

* Time Dilation
Begining with Loop Quantum Gravity theory, matter at the quanta level is a system of quanta loops and networks that are defined by how these particles interact with each other. Time is therefor quantized. By manipulating these networks in consistent patterns, it is possible to create a time dilation zone, or rather a zone within space where time moves more slowly. This process slows entropy at the quanta level.

Further developments enabled engineers to create even larger quantized zones, impacting time dilation. In combination of quantum linking and localized disruption on a star system's star, near the center of gravity, it is possible to slow time significantly for entire star systems.

** Dilation scale
The Dilation scale is a measurement of how time passes in relation from the manipulated time dilation zone to a zone of unmanipulated quanta. An unmanipulated quanta zone would be at dilation scale 1. A dilation scale 10 zone would view time passing within the dilation 1 zone ten times faster than how time passes within dilation 10.

** Time contraction
It was also found that quantized regions could be manipukated so that time would pass faster than time at dilation 1.

** Contraction scale
The Contraction scale measures how time passes viewed at dilation 1 to a zone in contraction scale. So someone viewing a zone of contraction 10 from dilation 1 would see time passing 10 times faster than that of dilation 1. Contraction involves speeding up the rate of entropy within the zone, and  thus contraction zones of greater than 10 have proven to be extremely volatile. Time contraction is rare, but was once weaponized during the Chronos wars.
